### ISSUE TITLE
gislab-machines: ldap_add: No such object

### ISSUE THREAD

**Issue by landam** [gislab-npo/gislab#480]
When registering new MAC on freshly installed unit I am getting:

```
sudo gislab-machines -a <mymacaddr>
Adding MAC address <mymacaddr>
No such object (32)
Matched DN: dc=gis,dc=lab
ldap_add: No such object (32)
        matched DN: dc=gis,dc=lab
```

**Comment by imincik** [comment]
MAC addresses storage was changed to LDAP just recently (https://github.com/gislab-npo/gislab/commit/eac2ce4582727f17ed5447c04863442b2c8aa83c)

**Comment by imincik** [comment]
But the tests for 'gislab-machines' in 'basic-configuration-test' are passing in my case.

Can you please try to run tests by yourself ('system/test.yml' playbook).

**Comment by landam** [comment]
```
TASK: [basic-configuration-test | Add machines] ******************************* 
failed: [gislab-unit-roudnice] => {"changed": false, "cmd": "gislab-machines -a 08:00:27:19:fc:b3,08:00:27:da:db:07", "delta": "0:00:00.035094", "end": "2016-01-25 15:58:15.978022", "rc": 32, "start": "2016-01-25 15:58:15.942928"}
stderr: No such object (32)
Matched DN: dc=gis,dc=lab
ldap_add: No such object (32)
        matched DN: dc=gis,dc=lab
stdout: Adding MAC address 08:00:27:19:fc:b3
...ignoring
TASK: [basic-configuration-test | Test if machines are correctly added] ******* 
failed: [gislab-unit-roudnice] => (item=hardware ethernet 08:00:27:19:fc:b3;) => {"changed": false, "cmd": "grep \"hardware ethernet 08:00:27:19:fc:b3;\" /etc/dhcp/gislab_known_machines.conf", "delta": "0:00:00.003648", "end": "2016-01-25 15:58:16.145074", "item": "hardware ethernet 08:00:27:19:fc:b3;", "rc": 1, "start": "2016-01-25 15:58:16.141426"}
...ignoring
failed: [gislab-unit-roudnice] => (item=hardware ethernet 08:00:27:da:db:07;) => {"changed": false, "cmd": "grep \"hardware ethernet 08:00:27:da:db:07;\" /etc/dhcp/gislab_known_machines.conf", "delta": "0:00:00.003617", "end": "2016-01-25 15:58:16.308784", "item": "hardware ethernet 08:00:27:da:db:07;", "rc": 1, "start": "2016-01-25 15:58:16.305167"}
...ignoring
TASK: [service-mail-test | Test if email to root user was forwarded to test superuser] *** 
failed: [gislab-unit-roudnice] => {"changed": false, "cmd": "sleep 2 && grep -r \"This is a test message sent by GIS.lab test b10cd67dbae31507ce7a5b06\" /mnt/home/test_mail_b10cd67dbae31507ce7a5b06/Mail/new", "delta": "0:00:02.007261", "end": "2016-01-25 15:58:24.888750", "rc": 2, "start": "2016-01-25 15:58:22.881489"}
stderr: grep: /mnt/home/test_mail_b10cd67dbae31507ce7a5b06/Mail/new: No such file or directory
...ignoring
```

**Comment by imincik** [comment]
Strange, my tests are OK with git version 300d2b33eb5890920a738a753f63d70d470d0e88 . What is your version ?

**Comment by landam** [comment]
To be sure I tried to reinstall the unit from scratch (create usb disc & run providers/gislab-unit/gislab-unit.yml and system/gislab.yml). Unfortunately gislab.yml fails with

```
TASK: [basic-configuration | Update apt cache] ******************************** 
failed: [gislab-unit-roudnice] => {"failed": true, "parsed": false}
invalid output was: SUDO-SUCCESS-picljavisdqcppjlbisgtznxbfixjlzp
Traceback (most recent call last):
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1453736181.61-63842394148062/apt", line 1907, in <module>
    main()
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1453736181.61-63842394148062/apt", line 507, in main
    cache.update()
  File "/usr/lib/python2.7/dist-packages/apt/deprecation.py", line 98, in deprecated_function
    return func(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 441, in update
    raise FetchFailedException(e)
apt.cache.FetchFailedException: E:GPG error: http://ubuntu.supp.name precise Release: The following signatures were invalid: NODATA 1 NODATA 2

FATAL: all hosts have already failed -- aborting
```

Shall I create a new issues?

**Comment by landam** [comment]
```
ansible --version
ansible 1.7.2
```

**Comment by imincik** [comment]
I meant GIS.lab version

**Comment by landam** [comment]
My GIS.lab version is 300d2b33

**Comment by imincik** [comment]
Update apt cache error looks like Ubuntu mirror problem.

**Comment by mpastor** [comment]
@landam could you send output of *lsldap* command, please?

**Comment by landam** [comment]
I tried to run system/gislab.yml with Ansible 1.9.2 and it fails on same place

```
TASK: [basic-configuration | Update apt cache] ******************************** 
failed: [gislab-unit-roudnice] => {"failed": true}
msg: Could not fetch updated apt files

FATAL: all hosts have already failed -- aborting
```

**Comment by landam** [comment]
Unit installation issue reported as #481

**Comment by landam** [comment]
OK, after fresh installation the problem disappeared.
