### ISSUE TITLE
unit installation fails (apt-cache)

### ISSUE THREAD

**Issue by landam** [gislab-npo/gislab#481]
To be sure I tried to reinstall the unit from scratch (create usb disc & run providers/gislab-unit/gislab-unit.yml and system/gislab.yml). Unfortunately gislab.yml fails with

```
TASK: [basic-configuration | Update apt cache] ******************************** 
failed: [gislab-unit-roudnice] => {"failed": true, "parsed": false}
invalid output was: SUDO-SUCCESS-picljavisdqcppjlbisgtznxbfixjlzp
Traceback (most recent call last):
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1453736181.61-63842394148062/apt", line 1907, in <module>
    main()
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1453736181.61-63842394148062/apt", line 507, in main
    cache.update()
  File "/usr/lib/python2.7/dist-packages/apt/deprecation.py", line 98, in deprecated_function
    return func(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 441, in update
    raise FetchFailedException(e)
apt.cache.FetchFailedException: E:GPG error: http://ubuntu.supp.name precise Release: The following signatures were invalid: NODATA 1 NODATA 2

FATAL: all hosts have already failed -- aborting
```

**Comment by landam** [comment]
With ansible 1.9.2 it fails on the same place:

```
TASK: [basic-configuration | Update apt cache] ******************************** 
failed: [gislab-unit-roudnice] => {"failed": true}
msg: Could not fetch updated apt files

FATAL: all hosts have already failed -- aborting
```

**Comment by imincik** [comment]
@landam, try to run apt-get update by hand. I guess it is a problem with your Ubuntu mirror.

**Comment by landam** [comment]
Right, it fails with the same error message. I removed from `source.list` all lines which starts with ```deb http://ubuntu.supp.name/ubuntu/``` and it works. How to fix installation process? The `source.list` files is regenerated.

**Comment by imincik** [comment]
I guess it will be just temporary problem with mirror.

**Comment by landam** [comment]
You are right, now it works.

**Comment by lfurtkevicova** [comment]
I tried to reinstall the unit from scratch. Unfortunately ``gislab.yml`` fails:

```
...
...

TASK: [basic-configuration | Move apt cache to storage directory] ************* 
ok: [gislab-unit-fem]

TASK: [basic-configuration | Deactivate original apt cache] ******************* 
changed: [gislab-unit-fem]

TASK: [basic-configuration | Activate shared apt cache] *********************** 
changed: [gislab-unit-fem]

TASK: [basic-configuration | Update apt cache] ******************************** 
failed: [gislab-unit-fem] => {"failed": true}
msg: Could not fetch updated apt files

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/ludka/gislab.retry

gislab-unit-fem            : ok=55   changed=9    unreachable=0    failed=1 
```

**Comment by landam** [comment]
@lfurtkevicova: the error was probably caused temporary problem with mirror. Closing.
